### PR TITLE
Add/Edit View Controller

### PR DESCRIPTION
**Pull request by CrystalKnightCodes**
Configured all outlets and buttons, and implemented frequency picker.

Still to do: Set up persistence for data, save button, connection to Pill model.

### CODE REVIEW

**Comment by sameeraleola** [comment]
Looks like you have conflicts with this PR. You have an outstanding PR that has already been approved (PR #13).  Please merge PR #13 first if it is causing the conflict.

**Comment by CrystalKnightCodes** [comment]
Ok. It was fine when I made the PR, but when I merged and rebased PR #13, it caused conflicts. I’ll go over it tomorrow and see if I can figure out where the conflict is.

**Comment by sameeraleola** [comment]
Sounds good! This is good practice. See you later. Have a great day!

**Review by sameeraleola — DISMISSED** [review]
The changes to PR#14 are straight forward and look good.

**Comment by sameeraleola** [comment]
We can deal with the conflict so that you can continue your progress.  It may be disappointing to have the conflict (especially with the abbreviated timeframe for your project completion) but it is a good experience.  We'll get to this first thing this evening (10/21).

**Review by sameeraleola — APPROVED** [review]
Glad you have your issues resolved.  Great progress.

**Pull request merged**
